%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: cam_fl
# Note: considers only projection matrix assuming that the images (keyframes from okvis) are pre-rectifed
projection_matrix:
    fx: 1242.0480207554092
    fy: 1242.0480207554092
    cx: 276.810977935791
    cy: 310.05108642578125

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 1.0

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#loop closure parameters
loop_closure: 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
fast_relocalization: 1
min_loop_num: 25


use_health: 1

# For undistorting original color image
is_stereo: 1
cam0:
    height: 600
    width: 800
    D: [-0.16289394, 0.08351833, 0.01227648, 0.0006859]
    K: [1138.83276975, 0.0, 308.17293738,
        0.0, 1139.59469807, 317.12897383,
        0.0, 0.0, 1.0]
    R: [0.9987608453733716, -0.024735976749058985, 0.043184548201154145,
        0.02417977658530305, 0.9996184201648292, 0.013354866957629642,
        -0.043498415526920325, -0.012294125485009934, 0.9989778487660305]

#R is rectification matrix