%YAML:1.0

#camera calibration 
model_type: PINHOLE
camera_name: slave1

#image resize factor. Note that, this factor MUST be same as OKVIS config file
resizeFactor: 0.5

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#loop closure parameters
loop_closure: 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
fast_relocalization: 1
min_loop_num: 25
ransac_reproj_threshold: 15.0

image_height: 1200
image_width: 1600
focal_length: [1149.52000993, 1150.57923685]
principal_point: [798.75530924, 577.20248548]
distortion_coefficients: [-0.16012168, 0.1020015, 0.00369027, 0.0034287]